<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <BuildWithMSBuildOnMono>true</BuildWithMSBuildOnMono>
    <Configurations>Debug;Release;</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FubarCoder.RestSharp.Portable.Core" Version="4.0.8" />
    <PackageReference Include="Ideine.LogsSender" Version="0.2.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
		<PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
		<PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
		<PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
		<PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
		<PackageReference Include="System.Net.Primitives" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\Resources\" />
  </ItemGroup>
</Project>
